markdown: kramdown
permalink: /blog/:year/:month/:title
name:         PaulRoho.com - On Developing Software
description:  Paul Rohorzka on developing software. Software that evolves. The craft of creating software.
url:          http://paulroho.com
urlhtml:	  PaulRoho<span class="text-muted">.com</span>
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      comments: true
  - scope:
      path: ""
      type: mae2014notes
    values:
      layout: "blog"
      comments: true
      prehead: Mobile App Europe 2014 Notes
      includeinindex: true
      
collections:
  mae2014notes:
    output: true
    permalink: /blog/2014/MobileAppEurope/:title
